import { prisma } from "../lib/prisma";


interface FishSpecies {
  name: string;
  scientificName: string;
  description: string;
  minLegalSize?: number; // cm
  habitat: string;
  bestBait?: string;
  bestTechniques?: string;
  imageUrl?: string;
  rarity: 'common' | 'uncommon' | 'rare' | 'very_rare' | 'legendary';
  category: 'freshwater' | 'saltwater' | 'brackish' | 'migratory';
  funFact?: string;
}

const fishSpecies: FishSpecies[] = [
  // ==================== FRESHWATER SPECIES ====================
  {
    name: 'Aborre',
    scientificName: 'Perca fluviatilis',
    description: 'Almindelig rovfisk i dansk ferskvand med karakteristiske striber',
    minLegalSize: undefined,
    habitat: 'Søer, åer og kystvand',
    bestBait: 'Orm, spinner, wobblers',
    bestTechniques: 'Spinfiskeri, bundstang',
    rarity: 'common',
    category: 'freshwater',
    funFact: 'Aborrer kan leve op til 25 år!',
  },
  {
    name: 'Brasen',
    scientificName: 'Abramis brama',
    description: 'Flad bundlevende fisk',
    minLegalSize: undefined,
    habitat: 'Søer, åer',
    bestBait: 'Orm, majs, pellets',
    bestTechniques: 'Bundstang, feeder',
    rarity: 'common',
    category: 'freshwater',
    funFact: 'Kan veje over 5 kg!',
  },
  {
    name: 'Bækørred',
    scientificName: 'Salmo trutta fario',
    description: 'Vildtlevende ørred i åer og bække',
    minLegalSize: 30,
    habitat: 'Bække, åer',
    bestBait: 'Orm, fluer, små spinnere',
    bestTechniques: 'Flugfiskeri, spinfiskeri',
    rarity: 'uncommon',
    category: 'freshwater',
    funFact: 'Bækørred og havørred er faktisk samme art!',
  },
  {
    name: 'Elritse',
    scientificName: 'Phoxinus phoxinus',
    description: 'Lille stimefisk',
    habitat: 'Hurtigstrømmende vand',
    rarity: 'common',
    category: 'freshwater',
  },
  {
    name: 'Flire',
    scientificName: 'Blicca bjoerkna',
    description: 'Ligner brasen men mindre',
    minLegalSize: undefined,
    habitat: 'Søer, åer',
    bestBait: 'Orm, majs',
    bestTechniques: 'Bundstang',
    rarity: 'uncommon',
    category: 'freshwater',
  },
  {
    name: 'Gedde',
    scientificName: 'Esox lucius',
    description: 'Danmarks største rovfisk i ferskvand med skarpe tænder',
    minLegalSize: 40,
    habitat: 'Søer, åer, fjorde',
    bestBait: 'Dødfisk, spinner, wobblers, jerkbait',
    bestTechniques: 'Spinfiskeri, flugfiskeri',
    rarity: 'common',
    category: 'freshwater',
    funFact: 'Gedder har over 700 tænder!',
  },
  {
    name: 'Skalle',
    scientificName: 'Rutilus rutilus',
    description: 'Populær fredelig fisk med røde finner',
    minLegalSize: undefined,
    habitat: 'Søer og åer',
    bestBait: 'Orm, majs, brød',
    bestTechniques: 'Bundstang, lette boltefiskeri',
    rarity: 'common',
    category: 'freshwater',
    funFact: 'Skaller kan danne stimer på over 1000 fisk',
  },
  {
    name: 'Karpe',
    scientificName: 'Cyprinus carpio',
    description: 'Stor fredelig fisk, populær blandt karpefiskere',
    minLegalSize: undefined,
    habitat: 'Søer, put & take søer',
    bestBait: 'Boilies, majs, pellets',
    bestTechniques: 'Karpestang med hair rig',
    rarity: 'common',
    category: 'freshwater',
    funFact: 'Karper kan blive over 100 år gamle!',
  },
  {
    name: 'Sandart',
    scientificName: 'Sander lucioperca',
    description: 'Natsaktiv rovfisk med store øjne',
    minLegalSize: 40,
    habitat: 'Store søer, åer, fjorde',
    bestBait: 'Levende fisk, gummifisk, wobblers',
    bestTechniques: 'Vertikalt fiskeri, spinfiskeri',
    rarity: 'uncommon',
    category: 'freshwater',
    funFact: 'Sandarter fanger bedst i skumringen og natten',
  },

  // SALMON & TROUT SPECIES
  {
    name: 'Havørred',
    scientificName: 'Salmo trutta',
    description: 'Sølvblank ørred fra havet',
    minLegalSize: 40,
    habitat: 'Kystvand, fjorde, åmundinger',
    bestBait: 'Fisk, blink, fluer',
    bestTechniques: 'Kystfiskeri, flugfiskeri',
    rarity: 'uncommon',
    category: 'migratory',
    funFact: 'Havørreder kan springe over 2 meter højt!',
  },
  {
    name: 'Laks',
    scientificName: 'Salmo salar',
    description: 'Stor anadrom fisk, konge blandt sportsfisk',
    minLegalSize: 60,
    habitat: 'Hav, åer under gydning',
    bestBait: 'Fluer, spinner',
    bestTechniques: 'Flugfiskeri, spinfiskeri',
    rarity: 'rare',
    category: 'migratory',
    funFact: 'Laks vender tilbage til præcis den å, hvor den blev født!',
  },
  {
    name: 'Regnbueørred',
    scientificName: 'Oncorhynchus mykiss',
    description: 'Indført art, populær i put & take søer',
    minLegalSize: undefined,
    habitat: 'Put & take søer, nogle åer',
    bestBait: 'Orm, pasta, powerbait',
    bestTechniques: 'Bundstang, spinfiskeri',
    rarity: 'common',
    category: 'freshwater',
    funFact: 'Regnbueørreder er oprindeligt fra Nordamerika',
  },
  {
    name: 'Bækørred',
    scientificName: 'Salmo trutta fario',
    description: 'Vildtlevende ørred i åer og bække',
    minLegalSize: 30,
    habitat: 'Bække, åer',
    bestBait: 'Orm, fluer, små spinnere',
    bestTechniques: 'Flugfiskeri, spinfiskeri',
    rarity: 'uncommon',
    category: 'freshwater',
    funFact: 'Bækørred og havørred er faktisk samme art!',
  },
  {
    name: 'Kildeørred',
    scientificName: 'Salvelinus fontinalis',
    description: 'Smuk nordamerikansk ørred',
    minLegalSize: undefined,
    habitat: 'Kolde bække og søer',
    bestBait: 'Fluer, orm',
    bestTechniques: 'Flugfiskeri',
    rarity: 'rare',
    category: 'freshwater',
    funFact: 'Kan tåle koldere vand end anden ørredarter',
  },
  {
    name: 'Sølvørred',
    scientificName: 'Salmo trutta',
    description: 'Stærk ørred fra søer',
    minLegalSize: undefined,
    habitat: 'Store søer',
    bestBait: 'Fisk, wobblers',
    bestTechniques: 'Trolling, spinfiskeri',
    rarity: 'uncommon',
    category: 'freshwater',
    funFact: 'Kan blive meget store i næringsrige søer',
  },

  // PIKE FAMILY
  {
    name: 'Helt',
    scientificName: 'Coregonus lavaretus',
    description: 'Sjælden laksefisk i dybe søer',
    minLegalSize: 36,
    habitat: 'Dybe kolde søer',
    bestBait: 'Små insekter, piller',
    bestTechniques: 'Pilk, flugfiskeri',
    rarity: 'very_rare',
    category: 'freshwater',
    funFact: 'En af Danmarks sjældneste fisk!',
  },
  {
    name: 'Heltling',
    scientificName: 'Coregonus albula',
    description: 'Lille slægtning til helten',
    minLegalSize: undefined,
    habitat: 'Søer',
    bestBait: 'Små madding',
    bestTechniques: 'Finesse fiskeri',
    rarity: 'rare',
    category: 'freshwater',
  },

  // BOTTOM DWELLERS
  {
    name: 'Brasen',
    scientificName: 'Abramis brama',
    description: 'Flad bundlevende fisk',
    minLegalSize: undefined,
    habitat: 'Søer, åer',
    bestBait: 'Orm, majs, pellets',
    bestTechniques: 'Bundstang, feeder',
    rarity: 'common',
    category: 'freshwater',
    funFact: 'Kan veje over 5 kg!',
  },
  {
    name: 'Flire',
    scientificName: 'Blicca bjoerkna',
    description: 'Ligner brasen men mindre',
    minLegalSize: undefined,
    habitat: 'Søer, åer',
    bestBait: 'Orm, majs',
    bestTechniques: 'Bundstang',
    rarity: 'common',
    category: 'freshwater',
  },
  {
    name: 'Rudskalle',
    scientificName: 'Scardinius erythrophthalmus',
    description: 'Smuk fisk med røde finner',
    minLegalSize: undefined,
    habitat: 'Vegetationsrige søer',
    bestBait: 'Orm, brød',
    bestTechniques: 'Let stang',
    rarity: 'uncommon',
    category: 'freshwater',
  },
  {
    name: 'Suder',
    scientificName: 'Tinca tinca',
    description: 'Kraftig bundlevende fisk',
    minLegalSize: undefined,
    habitat: 'Mudrede søer',
    bestBait: 'Orm, majs',
    bestTechniques: 'Bundstang',
    rarity: 'uncommon',
    category: 'freshwater',
    funFact: 'Sudere graver i mudderet efter føde',
  },

  // PREDATORS
  {
    name: 'Ål',
    scientificName: 'Anguilla anguilla',
    description: 'Mystisk vandrende fisk til Sargassohavet',
    minLegalSize: 45,
    habitat: 'Alle vandtyper',
    bestBait: 'Orm, dødfisk',
    bestTechniques: 'Bundstang om natten',
    rarity: 'uncommon',
    category: 'migratory',
    funFact: 'Ål fødes i Sargassohavet og svømmer til Danmark!',
  },
  {
    name: 'Malle',
    scientificName: 'Silurus glanis',
    description: 'Europas største ferskvandsfisk',
    minLegalSize: 75,
    habitat: 'Store søer, åer',
    bestBait: 'Stor fisk, blæksprutte',
    bestTechniques: 'Bundstang med stor madding',
    rarity: 'rare',
    category: 'freshwater',
    funFact: 'Kan veje over 100 kg og blive 3 meter lang!',
  },

  // SALTWATER SPECIES
  {
    name: 'Torsk',
    scientificName: 'Gadus morhua',
    description: 'Populær fisk i danske farvande',
    minLegalSize: 35,
    habitat: 'Kystvand, fjorde',
    bestBait: 'Tobis, fisk, orm',
    bestTechniques: 'Bundstang, pilk',
    rarity: 'common',
    category: 'saltwater',
    funFact: 'Kan blive over 1,5 meter lang!',
  },
  {
    name: 'Hornfisk',
    scientificName: 'Belone belone',
    description: 'Sommerfisk med grønt skelet',
    minLegalSize: undefined,
    habitat: 'Kystvand, fjorde om foråret',
    bestBait: 'Tobis, sildestrip',
    bestTechniques: 'Bombarda, flydefiskeri',
    rarity: 'common',
    category: 'migratory',
    funFact: 'Har grønne knogler!',
  },
  {
    name: 'Makrel',
    scientificName: 'Scomber scombrus',
    description: 'Hurtig rovfisk om sommeren',
    minLegalSize: undefined,
    habitat: 'Kystvand om sommeren',
    bestBait: 'Makrelpaternoster, pirk',
    bestTechniques: 'Spinfiskeri, paternoster',
    rarity: 'common',
    category: 'migratory',
    funFact: 'Kan svømme op til 80 km/t!',
  },
  {
    name: 'Havkat',
    scientificName: 'Anarhichas lupus',
    description: 'Kraftig fisk med store tænder',
    minLegalSize: 40,
    habitat: 'Dybere kystvand',
    bestBait: 'Fisk, rejer',
    bestTechniques: 'Bundstang',
    rarity: 'uncommon',
    category: 'saltwater',
    funFact: 'Kan knuse muslingeskaller med tænderne!',
  },
  {
    name: 'Havbars',
    scientificName: 'Dicentrarchus labrax',
    description: 'Ædel rovfisk fra sydligere farvande',
    minLegalSize: 42,
    habitat: 'Kystvand',
    bestBait: 'Fisk, wobblers',
    bestTechniques: 'Spinfiskeri',
    rarity: 'rare',
    category: 'saltwater',
    funFact: 'Bliver stadig hyppigere i danske farvande!',
  },

  // FLATFISH
  {
    name: 'Rødspætte',
    scientificName: 'Pleuronectes platessa',
    description: 'Almindelig fladfisk med orange pletter',
    minLegalSize: 27,
    habitat: 'Sandbund i kystvand',
    bestBait: 'Sandorm, muslinger',
    bestTechniques: 'Bundstang',
    rarity: 'common',
    category: 'saltwater',
    funFact: 'Har begge øjne på samme side!',
  },
  {
    name: 'Skrubbe',
    scientificName: 'Platichthys flesus',
    description: 'Tåler lavt saltindhold',
    minLegalSize: 25,
    habitat: 'Fjorde, kystvand',
    bestBait: 'Sandorm, muslinger',
    bestTechniques: 'Bundstang',
    rarity: 'common',
    category: 'brackish',
    funFact: 'Kan overleve i ferskvand!',
  },
  {
    name: 'Pighvarre',
    scientificName: 'Psetta maxima',
    description: 'Stor værdifuld fladfisk',
    minLegalSize: 32,
    habitat: 'Sandbund, kystvand',
    bestBait: 'Fisk, sandorm',
    bestTechniques: 'Bundstang',
    rarity: 'uncommon',
    category: 'saltwater',
    funFact: 'Kan veje over 20 kg!',
  },
  {
    name: 'Slethvarre',
    scientificName: 'Scophthalmus rhombus',
    description: 'Ligner pighvarre men uden pigge',
    minLegalSize: 30,
    habitat: 'Kystvand',
    bestBait: 'Fisk',
    bestTechniques: 'Bundstang',
    rarity: 'uncommon',
    category: 'saltwater',
  },
  {
    name: 'Tunge/søtunge',
    scientificName: 'Solea solea',
    description: 'Aflang fladfisk, delikatesse',
    minLegalSize: 24,
    habitat: 'Sandbund',
    bestBait: 'Sandorm',
    bestTechniques: 'Bundstang',
    rarity: 'uncommon',
    category: 'saltwater',
  },

  // More Freshwater Species
  {
    name: 'Grundling',
    scientificName: 'Gobio gobio',
    description: 'Lille bundfisk',
    habitat: 'Klart vand med grus',
    bestBait: 'Små orm',
    rarity: 'uncommon',
    category: 'freshwater',
  },
  {
    name: 'Elritse',
    scientificName: 'Phoxinus phoxinus',
    description: 'Lille stimefisk',
    habitat: 'Hurtigstrømmende vand',
    rarity: 'common',
    category: 'freshwater',
  },
  {
    name: 'Løje',
    scientificName: 'Alburnus alburnus',
    description: 'Lille overfladefisk',
    habitat: 'Søer, åer',
    rarity: 'common',
    category: 'freshwater',
  },
  {
    name: 'Smelt',
    scientificName: 'Osmerus eperlanus',
    description: 'Dufter af agurk!',
    habitat: 'Fjorde, kystvand',
    rarity: 'uncommon',
    category: 'brackish',
    funFact: 'Lugter af agurk når den er frisk!',
  },

  // Sturgeons (rare!)
  {
    name: 'Almindelig stør',
    scientificName: 'Acipenser sturio',
    description: 'Næsten uddød i danske farvande',
    minLegalSize: undefined,
    habitat: 'Kystzone (historisk)',
    rarity: 'legendary',
    category: 'migratory',
    funFact: 'Praktisk talt uddød - det ville være historisk at fange én!',
  },
  {
    name: 'Sterlet',
    scientificName: 'Acipenser ruthenus',
    description: 'Lille stør-art',
    habitat: 'Ferskvand (sjælden)',
    rarity: 'very_rare',
    category: 'freshwater',
  },

  // Exotic/rare catches
  {
    name: 'Guldørred',
    scientificName: 'Salmo trutta var. aurea',
    description: 'Gylden variant af ørred',
    habitat: 'Put & take søer',
    rarity: 'rare',
    category: 'freshwater',
    funFact: 'En farvevariant - meget sjælden at fange!',
  },
  {
    name: 'Tigerørred',
    scientificName: 'Salmo trutta x Salvelinus fontinalis',
    description: 'Hybrid mellem bækørred og kildeørred',
    habitat: 'Put & take søer',
    rarity: 'very_rare',
    category: 'freshwater',
    funFact: 'En steril hybrid - kan ikke formere sig!',
  },

  // More saltwater
  {
    name: 'Sej/mørksej',
    scientificName: 'Pollachius virens',
    description: 'Stærk torskefisk',
    minLegalSize: 35,
    habitat: 'Åbent hav, dybere vand',
    rarity: 'uncommon',
    category: 'saltwater',
  },
  {
    name: 'Hvilling',
    scientificName: 'Merlangius merlangus',
    description: 'Mindre torskefisk',
    minLegalSize: 27,
    habitat: 'Kystvand',
    rarity: 'common',
    category: 'saltwater',
  },
  {
    name: 'Kuller',
    scientificName: 'Melanogrammus aeglefinus',
    description: 'Torskefisk med sort plet',
    minLegalSize: 30,
    habitat: 'Dybere vand',
    rarity: 'uncommon',
    category: 'saltwater',
  },
  {
    name: 'Multe',
    scientificName: 'Mullus surmuletus',
    description: 'Rød fisk med skæg',
    habitat: 'Sandeller grus bund',
    rarity: 'uncommon',
    category: 'saltwater',
  },

  // Wrasses
  {
    name: 'Berggylt',
    scientificName: 'Labrus bergylta',
    description: 'Stor læbefisk',
    habitat: 'Stenrev',
    rarity: 'uncommon',
    category: 'saltwater',
  },

  // Sharks (very rare in Danish waters!)
  {
    name: 'Pighaj',
    scientificName: 'Squalus acanthias',
    description: 'Lille haj i danske farvande',
    habitat: 'Åbent hav',
    rarity: 'very_rare',
    category: 'saltwater',
    funFact: 'Har giftige pigge foran rygfinnerne!',
  },
  {
    name: 'Gråhaj',
    scientificName: 'Hexanchus griseus',
    description: 'Dybtvandshai',
    habitat: 'Dybt vand (ekstremt sjælden)',
    rarity: 'legendary',
    category: 'saltwater',
    funFact: 'Hvis du fanger denne, er du legendarisk!',
  },

  // Garpike etc.
  {
    name: 'Næse',
    scientificName: 'Chondrostoma nasus',
    description: 'Strømlevende karpefisk',
    habitat: 'Åer med strøm',
    rarity: 'uncommon',
    category: 'freshwater',
  },
  {
    name: 'Stalling',
    scientificName: 'Idus idus',
    description: 'Stor karpefisk',
    habitat: 'Søer, åer',
    rarity: 'uncommon',
    category: 'freshwater',
  },
  {
    name: 'Sperling',
    scientificName: 'Leuciscus aspius',
    description: 'Stor overflade-rovfisk',
    habitat: 'Store søer, åer',
    rarity: 'rare',
    category: 'freshwater',
  },
  {
    name: 'Rimte',
    scientificName: 'Vimba vimba',
    description: 'Vandrefisk der gyder i åer',
    habitat: 'Åer, kystvand',
    rarity: 'rare',
    category: 'migratory',
  },
  {
    name: 'Hork',
    scientificName: 'Esox lucius',
    description: 'Mindre gedde',
    habitat: 'Samme som gedde',
    rarity: 'common',
    category: 'freshwater',
  },

  // Bottom feeders & specialists
  {
    name: 'Lubbe/lyssej',
    scientificName: 'Lota lota',
    description: 'Eneste torskefisk i ferskvand',
    habitat: 'Kolde søer og åer',
    rarity: 'rare',
    category: 'freshwater',
    funFact: 'Gyder midt om vinteren under isen!',
  },
  {
    name: 'Ålekvabbe',
    scientificName: 'Zoarces viviparus',
    description: 'Føder levende unger!',
    habitat: 'Kystvand mellem sten',
    rarity: 'uncommon',
    category: 'saltwater',
    funFact: 'Føder levende unger i stedet for at lægge æg!',
  },
  {
    name: 'Tangkvabbe',
    scientificName: 'Zoarces viviparus',
    description: 'Lever mellem tang',
    habitat: 'Tang',
    rarity: 'common',
    category: 'saltwater',
  },

  // Exotic species (very rare or legendary)
  {
    name: 'Guldfisk/sølvkarusse',
    scientificName: 'Carassius auratus',
    description: 'Undslupne prydguldfisk',
    habitat: 'Damme, søer',
    rarity: 'uncommon',
    category: 'freshwater',
  },
  {
    name: 'Solaborre',
    scientificName: 'Lepomis gibbosus',
    description: 'Farvestrålende invasiv art',
    habitat: 'Varme søer',
    rarity: 'rare',
    category: 'freshwater',
    funFact: 'Invasiv art fra Nordamerika',
  },
  {
    name: 'Solskinsbars',
    scientificName: 'Micropterus salmoides',
    description: 'Amerikansk black bass',
    habitat: 'Put & take søer (sjælden)',
    rarity: 'very_rare',
    category: 'freshwater',
    funFact: 'Meget aggressiv rovfisk!',
  },

  // Herrings
  {
    name: 'Sild',
    scientificName: 'Clupea harengus',
    description: 'Klassisk dansk sild',
    habitat: 'Kystvand',
    rarity: 'common',
    category: 'saltwater',
  },
  {
    name: 'Brisling',
    scientificName: 'Sprattus sprattus',
    description: 'Lille sild',
    habitat: 'Kystvand',
    rarity: 'common',
    category: 'saltwater',
  },

  // Tunas (super rare!)
  {
    name: 'Tun',
    scientificName: 'Thunnus thynnus',
    description: 'Blåfinnet tun - ekstremt sjælden',
    habitat: 'Åbent hav (ekstremt sjældent)',
    rarity: 'legendary',
    category: 'saltwater',
    funFact: 'Hvis du fanger denne i Danmark, er det historisk!',
  },

  // Add rest as common/uncommon with minimal data
  {
    name: 'Ising',
    scientificName: 'Leuciscus leuciscus',
    description: 'Strømlevende fredsømmer',
    habitat: 'Hurtigtstrømmende åer',
    rarity: 'uncommon',
    category: 'freshwater',
  },
  {
    name: 'Knude',
    scientificName: 'Leuciscus idus',
    description: 'Mindre karpefisk',
    habitat: 'Søer, åer',
    rarity: 'common',
    category: 'freshwater',
  },
  {
    name: 'Guldfisk',
    scientificName: 'Carassius auratus',
    description: 'Undslupne prydguldfisk',
    habitat: 'Damme, søer',
    rarity: 'uncommon',
    category: 'freshwater',
  },
  {
    name: 'Karusse',
    scientificName: 'Carassius carassius',
    description: 'Robust karpefisk',
    habitat: 'Småsøer og damme',
    rarity: 'common',
    category: 'freshwater',
  },
  {
    name: 'Rimte',
    scientificName: 'Vimba vimba',
    description: 'Vandrefisk der gyder i åer',
    habitat: 'Åer, kystvand',
    rarity: 'uncommon',
    category: 'migratory',
  },
  {
    name: 'Skælkarpe',
    scientificName: 'Cyprinus carpio',
    description: 'Karpe med normale skæl',
    habitat: 'Søer',
    rarity: 'common',
    category: 'freshwater',
  },
  {
    name: 'Spejlkarpe',
    scientificName: 'Cyprinus carpio',
    description: 'Karpe med få store skæl',
    habitat: 'Søer',
    rarity: 'common',
    category: 'freshwater',
  },

  // ==================== SALTWATER SPECIES ====================
  {
    name: 'Berggylt',
    scientificName: 'Labrus bergylta',
    description: 'Stor læbefisk',
    habitat: 'Stenrev',
    rarity: 'uncommon',
    category: 'saltwater',
  },
  {
    name: 'Blåstak',
    scientificName: 'Molva dypterygia',
    description: 'Stor torskefisk',
    habitat: 'Dybere vand',
    rarity: 'rare',
    category: 'saltwater',
  },
  {
    name: 'Fjæsing',
    scientificName: 'Trachinus draco',
    description: 'Giftig bundfisk',
    habitat: 'Sandbund i kystvand',
    rarity: 'uncommon',
    category: 'saltwater',
    funFact: 'Har giftige pigge - pas på!',
  },
  {
    name: 'Glyse',
    scientificName: 'Pollachius pollachius',
    description: 'Torskefisk med mørk ryg',
    minLegalSize: 30,
    habitat: 'Kystvand, stenrev',
    rarity: 'uncommon',
    category: 'saltwater',
  },
  {
    name: 'Grå knurhane',
    scientificName: 'Eutrigla gurnardus',
    description: 'Bundfisk med store brystfinner',
    habitat: 'Sandbund',
    rarity: 'uncommon',
    category: 'saltwater',
    funFact: 'Kan lave lyde med svømmeblæren!',
  },
  {
    name: 'Havkarusse',
    scientificName: 'Carassius carassius',
    description: 'Saltvandsvariant af karusse',
    habitat: 'Kystvand',
    rarity: 'rare',
    category: 'saltwater',
  },
  {
    name: 'Hestemakrel',
    scientificName: 'Trachurus trachurus',
    description: 'Stimer af rovfisk',
    habitat: 'Åbent hav',
    rarity: 'uncommon',
    category: 'saltwater',
  },
  {
    name: 'Ising',
    scientificName: 'Leuciscus leuciscus',
    description: 'Strømlevende fredsfisk',
    habitat: 'Hurtigtstrømmende åer',
    rarity: 'uncommon',
    category: 'saltwater',
  },
  {
    name: 'Kulmule',
    scientificName: 'Micromesistius poutassou',
    description: 'Lille torskefisk',
    habitat: 'Dybere vand',
    rarity: 'uncommon',
    category: 'saltwater',
  },
  {
    name: 'Lange',
    scientificName: 'Molva molva',
    description: 'Lang torskefisk',
    minLegalSize: 60,
    habitat: 'Dybere vand',
    rarity: 'rare',
    category: 'saltwater',
  },
  {
    name: 'Panserulk',
    scientificName: 'Agonus cataphractus',
    description: 'Lille fisk med benplader',
    habitat: 'Kystvand',
    rarity: 'uncommon',
    category: 'saltwater',
  },
  {
    name: 'Rødtunge',
    scientificName: 'Microstomus kitt',
    description: 'Fladfisk med rødlig farve',
    minLegalSize: 23,
    habitat: 'Sandbund',
    rarity: 'uncommon',
    category: 'saltwater',
  },
  {
    name: 'Sortkutling',
    scientificName: 'Pollachius pollachius',
    description: 'Torskefisk',
    habitat: 'Kystvand',
    rarity: 'uncommon',
    category: 'saltwater',
  },
  {
    name: 'Sortvels',
    scientificName: 'Catulus catulus',
    description: 'Lille hajeart',
    habitat: 'Dybere vand',
    rarity: 'rare',
    category: 'saltwater',
  },
  {
    name: 'Stenbider',
    scientificName: 'Cyclopterus lumpus',
    description: 'Rund fisk med sugekop',
    habitat: 'Stenrev',
    rarity: 'uncommon',
    category: 'saltwater',
    funFact: 'Kan klæbe sig fast til sten!',
  },
  {
    name: 'Tangsnarre',
    scientificName: 'Symphodus melops',
    description: 'Farvestrålende læbefisk',
    habitat: 'Tang og stenrev',
    rarity: 'common',
    category: 'saltwater',
  },
  {
    name: 'Tangspræl',
    scientificName: 'Pholis gunnellus',
    description: 'Lang tynd fisk',
    habitat: 'Under sten i tang',
    rarity: 'common',
    category: 'saltwater',
  },
  {
    name: 'Tobis',
    scientificName: 'Ammodytes tobianus',
    description: 'Vigtig fødekilde for andre fisk',
    habitat: 'Sandbund',
    rarity: 'common',
    category: 'saltwater',
  },
  {
    name: 'Ulk',
    scientificName: 'Myoxocephalus scorpius',
    description: 'Bundfisk med stort hoved',
    habitat: 'Stenrev, kystvand',
    rarity: 'common',
    category: 'saltwater',
  },
];

export async function seedFiskeDex() {
  for (const fish of fishSpecies) {
    try {
      await prisma.species.upsert({
        where: { name: fish.name },
        update: {
          scientificName: fish.scientificName,
          description: fish.description,
          minLegalSize: fish.minLegalSize,
          habitat: fish.habitat,
          bestBait: fish.bestBait,
          bestTechniques: fish.bestTechniques,
          imageUrl: fish.imageUrl,
          rarity: fish.rarity,
        },
        create: {
          name: fish.name,
          scientificName: fish.scientificName,
          description: fish.description,
          minLegalSize: fish.minLegalSize,
          habitat: fish.habitat,
          bestBait: fish.bestBait,
          bestTechniques: fish.bestTechniques,
          imageUrl: fish.imageUrl,
          rarity: fish.rarity,
        },
      });

      const rarityEmoji = {
        common: '⚪',
        uncommon: '🟢',
        rare: '🔵',
        very_rare: '🟣',
        legendary: '🟠',
      };

    } catch (error) {
      console.error(`❌ Failed to seed ${fish.name}:`, error);
    }
  }

  const speciesCount = await prisma.species.count();
}

// Run if called directly
if (require.main === module) {
  seedFiskeDex()
    .then(() => {
      process.exit(0);
    })
    .catch((error) => {
      console.error('Error seeding FiskeDex:', error);
      process.exit(1);
    });
}

export { fishSpecies };
